config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exit_deliveries
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get '/privacy' => 'pages#privacy'
  get '/terms' => 'pages#terms'
  get '/cookies' => 'pages#cookies'
  get '/lead_search' => 'lead#lead_search'
  namespace 'api', defaults: { format: :json } do
    namespace 'v1' do
      get '/redirect_url' => 'redirect#redirect_url'
      get '/exit_deliveries' => 'redirect#exit_deliveries'
    end
  end
  get '/:page_name' => 'pages#show'
end

app/models/exit_delivery.rb
class ExitDelivery < ApplicationRecord
  validate :validate_percentage
  validate :validate_priority
  validate :is_already_default

  scope :sold, -> { where(status: "sold", is_default: false).order(priority: :asc) }
  scope :unsold, -> { where(status: "unsold", is_default: false).order(priority: :asc) }
  scope :active_sold, -> { where(status: "sold", is_default: false, operational: "active", functional: "active").order(priority: :asc) }
  scope :active_unsold, -> { where(status: "unsold", is_default: false, operational: "active", functional: "active").order(priority: :asc) }

  scope :active, -> { where(is_default: false, operational: "active", functional: "active").order(priority: :asc) }
  scope :active_sold_with_no_source_smartphone, -> { where(status: "sold", is_default: false, operational: "active",is_mobile: true, functional: "active", source: []|| [""]).order(priority: :asc) }
  scope :active_unsold_with_no_source_smartphone, -> { where(status: "unsold", is_default: false, operational: "active", functional: "active",is_mobile: true, source: [] || [""]).order(priority: :asc) }

  scope :active_sold_with_no_source_desktop, -> { where(status: "sold", is_default: false, operational: "active",is_mobile: false, functional: "active", source: []|| [""]).order(priority: :asc) }
  scope :active_unsold_with_no_source_desktop, -> { where(status: "unsold", is_default: false, operational: "active", functional: "active",is_mobile: false, source: [] || [""]).order(priority: :asc) }

  scope :is_mobile, -> {where(is_mobile: true)}
  scope :is_desktop, -> {where(is_mobile: false)}
  enum source_rule: {Is: 0, Contains: 1, Does_not_contains: 2 }

  def self.match_type_query(urls, sourceVal)
    @exit_urls_ids = []
    urls.each do |url|
      source_exists, sourceCount = check_existence(url, sourceVal)

      if url.source_rule == 'Is' and sourceCount == 1 && source_exists
        @exit_urls_ids.push(url.id)
      elsif url.source_rule == 'Contains' and source_exists
        debugger
        @exit_urls_ids.push(url.id)
      elsif url.source_rule == 'Does not contains' and !source_exists
        @exit_urls_ids.push (url.id)
      elsif url.source.empty?
        @exit_urls_ids.push (url.id)
      end
    end
    return @exit_urls_ids
  end

  def self.check_existence(url, sourceVal)
    check = url.source.map{ |src| src.downcase.include?(sourceVal.downcase) }
    check = check.include?(true)
    return [check, url.source.length]
  end

  def operational?
    self.operational == "active"
  end

  def functional?
    self.functional == "active"
  end

  def is_already_default
    is_default = ExitDelivery.where.not(id: self.id).where(status: self.status).where(functional: "active", is_default: true).any? && self.is_default
    if is_default
      errors.add(
        :is_default, ": One only URl can be default"
      )
    end
  end

  def validate_percentage
    return if self.is_default

    if self.source.present?
      total_percent = ExitDelivery.where.not(id: self.id).where(status: self.status, operational: "active", functional: "active" , is_default: false, is_mobile: self.is_mobile).filter{|url| url if (url.source & self.source).present?}.pluck(:percentage).sum
    else
      total_percent = ExitDelivery.where.not(id: self.id).where(status: self.status, operational: "active", functional: "active" , is_default: false, is_mobile: self.is_mobile, source: []).pluck(:percentage).sum
    end

    unless total_percent + self.percentage <= 100
      errors.add(
        :percentage, ": Enter less than or equal to #{100 - total_percent}"
      )
    end
  end

  def validate_priority
     priorities = ExitDelivery.where.not(id: self.id).where(status: self.status, is_mobile: self.is_mobile).pluck(:priority)
    if priorities.include?(self.priority)
      errors.add(
        :priority, ": Already taken"
      )
    end
  end
end

app/controllers/exit_deliveries_controller.rb
class ExitDeliveriesController < ApplicationController
  before_action :set_exit_delivery, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /exit_deliveries or /exit_deliveries.json
  def index
    if params[:status]
      @exit_deliveries = ExitDelivery.where(status: params[:status])
    elsif params[:functional]
      @exit_deliveries = ExitDelivery.where(functional: params[:functional])
    else
      @exit_deliveries = ExitDelivery.all
    end
  end

  # GET /exit_deliveries/1 or /exit_deliveries/1.json
  def show
  end

  # GET /exit_deliveries/new
  def new
    @exit_delivery = ExitDelivery.new
  end

  # GET /exit_deliveries/1/edit
  def edit
  end

  # POST /exit_deliveries or /exit_deliveries.json
  def create
    @exit_delivery = ExitDelivery.new(exit_delivery_params)

    respond_to do |format|
      if @exit_delivery.save
        format.html { redirect_to @exit_delivery, notice: "Exit delivery was successfully created." }
        format.json { render :show, status: :created, location: @exit_delivery }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exit_delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exit_deliveries/1 or /exit_deliveries/1.json
  def update
    respond_to do |format|
      if @exit_delivery.update(exit_delivery_params)
        format.html { redirect_to @exit_delivery, notice: "Exit delivery was successfully updated." }
        format.json { render :show, status: :ok, location: @exit_delivery }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exit_delivery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exit_deliveries/1 or /exit_deliveries/1.json
  def destroy
    @exit_delivery.destroy
    respond_to do |format|
      format.html { redirect_to exit_deliveries_url, notice: "Exit delivery was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exit_delivery
      @exit_delivery = ExitDelivery.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def exit_delivery_params
      params.require(:exit_delivery).permit(:url, :name, :percentage,
        :status, :priority, :cap, :count, :operational, :is_default, :is_mobile, :source_rule,
        :functional).merge(copy_percentage: params[:exit_delivery][:percentage], source: params[:exit_delivery][:source].reject(&:blank?))
    end
end

app/helpers/exit_deliveries_helper.rb
module ExitDeliveriesHelper
end

app/views/exit_deliveries/_filters.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h6>Status:</h6>
      <%= link_to "Sold", exit_deliveries_path(status: "sold"), class: "btn btn-info" %>
      <%= link_to "Unsold", exit_deliveries_path(status: "unsold"), class: "btn btn-info" %>
    </div>
    <div class="col-3">
      <h6>Functional:</h6>
      <%= link_to "Active", exit_deliveries_path(functional: "active"), class: "btn btn-info" %>
      <%= link_to "Disable", exit_deliveries_path(functional: "disable"), class: "btn btn-info" %>
    </div>
    <div class="col-6 text-right">
      <h6>All Records:</h6>
      <a href="/exit_deliveries" class="btn btn-info">Reset</a>
    </div>
  </div>
</div>

app/views/exit_deliveries/_form.html.erb
<%= javascript_pack_tag 'exit_delivery', 'data-turbolinks-track': true, defer: true %>
<%= form_with(model: exit_delivery, local: true) do |form| %>
  <div class="row align-items-center justify-content-center">
    <% if exit_delivery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(exit_delivery.errors.count, "error") %> prohibited this exit_delivery from being saved:</h2>

        <ul>
          <% exit_delivery.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field form-group col-lg-10">
      <%= form.label :name, :class=> 'control-label' %>
      <%= form.text_field :name, :required => true, :class=> 'form-control'%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :url, :class=> 'control-label' %>
      <%= form.text_field :url, :required => true, :class=> 'form-control'%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :percentage, :class=> 'control-label' %>
      <%= form.number_field :percentage, :step => "0.01", :required => true, :class=> 'form-control' %>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :priority, :class=> 'control-label' %>
      <%= form.number_field :priority, :required => true, :class=> 'form-control'%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :cap, :class=> 'control-label' %>
      <%= form.number_field :cap, :class=> 'form-control' %>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :source, :class=> 'control-label' %>
      <%= form.select :source, options_for_select(exit_delivery.source, exit_delivery.source), {},{:multiple => true, class: 'form-control source'} %>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :source_rule%>
      <%= form.select :source_rule, ['Is', 'Contains', 'Does_not_contains']%>
    </div>


    <div class="field d-none" >
      <%= form.label :count, :class=> 'control-label'%>
      <%= form.number_field :count, :readonly => true, :class=> 'form-control'%>
    </div>

    <div class="field d-none">
      <%= form.label :operational, :class=> 'control-label' %>
      <%= form.text_field :operational, :readonly => true, :class=> 'form-control'%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :functional%>
      <%= form.select :functional, ['active', 'disable']%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :status%>
      <%= form.select :status, ['sold','unsold']%>
    </div>

    <div class="field form-group col-lg-10">
      <%= form.label :is_mobile %>
      <%= form.check_box :is_mobile %>
    </div>


    <div class="field form-group col-lg-10">
      <%= form.label :is_default %>
      <%= form.check_box :is_default %>
    </div>

    <div class="actions d-flex justify-content-end col-lg-10 ">
      <%= form.submit "Save Redirect URL", :class=> "btn btn-primary mr-2"  %>
      <%= link_to 'Back', exit_deliveries_path, :class=> 'btn btn-danger', data: { turbolinks: false } %>
    </div>
  </div>
<% end %>

app/views/exit_deliveries/edit.html.erb
<h1 class="text-center">Edit Redirect URL</h1>
<div class="container">
  <%= render 'form', exit_delivery: @exit_delivery %>
</div>

app/views/exit_deliveries/index.html.erb
<div class="mx-3">
  <div class="exit-delivery">
    <p id="notice"><%= notice %></p>
    <h1 class="text-center">Redirect URLS</h1>
    <div class="container pb-3">
      <%= render "exit_deliveries/filters" %>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>Url</th>
          <th>Today Count</th>
          <th>Total Count</th>
          <th>Default</th>
          <th>Percentage</th>
          <th>Status</th>
          <th>Priority</th>
          <th>Cap</th>
          <th>Source</th>
          <th>functional</th>
          <th>For Mobile</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @exit_deliveries.each do |exit_delivery| %>
          <tr>
            <td><%= exit_delivery.name %></td>
            <td><%= exit_delivery.url %></td>
            <td><%= exit_delivery.count %></td>
            <td><%= exit_delivery.total_count %></td>
            <td><%= exit_delivery.is_default %></td>
            <td><%= exit_delivery.percentage %></td>
            <td><%= exit_delivery.status %></td>
            <td><%= exit_delivery.priority %></td>
            <td><%= exit_delivery.cap %></td>
            <td><%= exit_delivery.source %></td>
            <td><%= exit_delivery.functional %></td>
            <td><%= exit_delivery.is_mobile %></td>
            <td><%= link_to 'Show', exit_delivery, :class => "btn btn-success btn-xs text-white btns-text" %></td>
            <td><%= link_to 'Edit', edit_exit_delivery_path(exit_delivery),
            :class => "btn btn-primary btn-xs text-white btns-text" %></td>
            <td><%= link_to 'Destroy', exit_delivery,:class => "btn btn-danger btn-xs text-white btns-text", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <br>
    <div class="text-center">
      <%= link_to 'New Exit Delivery', new_exit_delivery_path, :class => "btn btn-info btn-xs text-white" %>
    </div>
  </div>
</div>

app/views/exit_deliveries/new.html.erb
<h1 class="text-center">New Redirect URL</h1>
<div class="container">
  <%= render 'form', exit_delivery: @exit_delivery %>
</div>

app/views/exit_deliveries/show.html.erb
<div class="container">
  <div class="exit-delivery">
    <p id="notice"><%= notice %></p>
    <table class="table table-bordered w-100">
      <tr>
        <th>Name</th>
        <td><%= @exit_delivery.name %></td>
      </tr>
      <tr>
        <th>Url</th>
        <td><%= @exit_delivery.url %></td>
      </tr>
      <tr>
        <th>Percentage</th>
        <td><%= @exit_delivery.percentage %></td>
      </tr>
      <tr>
        <th>Status</th>
        <td><%= @exit_delivery.status %></td>
      </tr>
      <tr>
        <th>Priority</th>
        <td><%= @exit_delivery.priority %></td>
      </tr>
      <tr>
        <th>Cap</th>
        <td><%= @exit_delivery.cap %></td>
      </tr>
      <tr>
        <th>Source</th>
        <td><%= @exit_delivery.source %></td>
      </tr>
      <tr>
        <th>functional</th>
        <td><%= @exit_delivery.functional %></td>
      </tr>
      <tr>
        <th>Is Mobile</th>
        <td><%= @exit_delivery.is_mobile %></td>
      </tr>
    </table>
    <div class="text-center">
      <%= link_to 'Edit', edit_exit_delivery_path(@exit_delivery), :class=>'btn btn-primary px-4 text-white' %> |
      <%= link_to 'Back', exit_deliveries_path, :class=>'btn btn-primary px-4 text-white' %>
    </div>
  </div>
</div>